modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL = "${issue_url}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${homepage_url}"
logoFile = "${mod_name}.png"
credits = "${author}"
authors = "${author}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${description}'''

# Forge Dependency
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
